language: python
python:
  # - 2.6 -- tested, but only for few Django versions
  - 2.7
  - 3.2
  - 3.3
  - 3.4
  - pypy
  - pypy3

env:
  - DJANGO="django<1.6"
  - DJANGO="django<1.7"
  - DJANGO="django<1.8"
  - DJANGO=https://github.com/django/django/tarball/master

matrix:
  allow_failures:
    - env: DJANGO=https://github.com/django/django/tarball/master
  include:
    - python: 2.6
      env: DJANGO="django<1.5"
    - python: 2.7
      env: DJANGO="django<1.5"
    - python: pypy
      env: DJANGO="django<1.5"
    - python: 2.6
      env: DJANGO="django<1.6"
    - python: 2.6
      env: DJANGO="django<1.7"

install:
  - travis_retry pip install $DJANGO
  - travis_retry pip install -e .
  - travis_retry pip install "django-smoked[tests]"
  - travis_retry pip install "django-smoked[qa]"

script:
  - python --version
  - django-admin.py --version
  - py.test --cov smoked --cov-report term-missing -v tests/

after_success:
  - coveralls
